name = "agio"
main = "src/bin/app.ts"
compatibility_date = "2024-12-25"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
ANTHROPIC_TOKEN = "xxx"
DISCORD_TOKEN = "xxx"
DISCORD_APPLICATION_ID = "xxx"
DISCORD_PUBLIC_KEY = "xxx"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
